"use client";

import { useEffect, useState } from "react";

import Sidebar from "../../components/Sidebar";
import FileSelector from "../../components/FileSelector";
import CSVPreviewTable from "../../components/CSVPreviewTable";
import StatCard from "../../components/StatCard";

import {
  getCRMFiles,
  previewCRMFile,
} from "../../../lib/api";

import {
  Database,
  CheckCircle,
  AlertCircle,
  FileText,
} from "lucide-react";

export default function CRMPage() {
  const [files, setFiles] = useState<string[]>([]);

  const [selectedFile, setSelectedFile] =
    useState<string | null>(null);

  const [rows, setRows] = useState<any[]>([]);

  // Added states
  const [totalRecords, setTotalRecords] = useState(0);
  const [mappedRecords, setMappedRecords] = useState(0);

  const loadCRMFiles = async () => {
    try {
      const response = await getCRMFiles();

      setFiles(response.data);

      if (
        response.data.length > 0 &&
        !selectedFile
      ) {
        previewFile(response.data[0]);
      }
    } catch (error) {
      console.error(error);
    }
  };

  const previewFile = async (fileName: string) => {
    try {
      setSelectedFile(fileName);

      const response = await previewCRMFile(fileName);

      // Updated according to new backend response
      setRows(response.data.records);
      setTotalRecords(response.data.totalRecords);
      setMappedRecords(response.data.mappedRecords);
    } catch (error) {
      console.error(error);
    }
  };

  useEffect(() => {
    loadCRMFiles();
  }, []);

  return (
    <main className="min-h-screen bg-[#020617] text-white flex">
      <Sidebar />

      <section className="flex-1 overflow-y-auto p-8">

        {/* Header */}

        <div className="rounded-[32px] border border-white/10 bg-white/5 p-8 backdrop-blur-xl">

          <p className="text-sm uppercase tracking-[0.3em] text-emerald-400">
            CRM Leads
          </p>

          <h1 className="mt-2 text-4xl font-semibold">
            Generated CRM Files
          </h1>

          <p className="mt-3 max-w-2xl text-slate-400">
            Browse all CRM files generated by AI. Preview records and
            review mapping results before importing them into your CRM.
          </p>

        </div>

        {/* Statistics */}

        <div className="mt-8 grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4">

          <StatCard
            title="CRM Files"
            value={files.length}
            icon={<Database />}
          />

          <StatCard
            title="Total Records"
            value={totalRecords}
            icon={<FileText />}
          />

          <StatCard
            title="Mapped Records"
            value={mappedRecords}
            icon={<CheckCircle />}
          />

          <StatCard
            title="Skipped Records"
            value={totalRecords - mappedRecords}
            icon={<AlertCircle />}
          />

        </div>

        {/* Main Content */}

        <div className="mt-8 grid grid-cols-12 gap-6">

          {/* Left */}

          <div className="col-span-4">

            <FileSelector
              title="CRM Files"
              subtitle="Select a CRM CSV to preview."
              files={files}
              selectedFile={selectedFile}
              onSelect={previewFile}
            />

          </div>

          {/* Right */}

          <div className="col-span-8 rounded-[30px] border border-white/10 bg-[#0f172a] p-6">

            <div className="mb-6">

              <h2 className="text-xl font-semibold">
                CRM Preview
              </h2>

              <p className="mt-2 text-sm text-slate-400">
                {selectedFile
                  ? selectedFile
                  : "No CRM file selected"}
              </p>

            </div>

            <CSVPreviewTable rows={rows} />

          </div>

        </div>

      </section>

    </main>
  );
}
